# Generated by Django 4.2.19 on 2025-02-19 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('designers_pics', models.ImageField(blank=True, null=True, upload_to='designers_pics', verbose_name='Photo')),
            ],
            options={
                'ordering': ('surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('item_code', models.CharField(max_length=10, unique=True, verbose_name='Item code')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('dresses_pics', models.ImageField(blank=True, null=True, upload_to='dresses_pics', verbose_name='Photo')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresscode.designer')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default-user.png', upload_to='profile_pics')),
                ('iban', models.CharField(max_length=30, unique=True, verbose_name='IBAN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DressRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start day')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return day')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rented', 'rented'), ('returned', 'returned')], default='pending', help_text='Dress rent status', max_length=20, verbose_name='Status')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresscode.dress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dress',
            name='size',
            field=models.ManyToManyField(to='dresscode.size'),
        ),
        migrations.AddField(
            model_name='dress',
            name='style',
            field=models.ManyToManyField(to='dresscode.style'),
        ),
    ]
