# Generated by Django 4.2.19 on 2025-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode', '0004_alter_dressrental_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iban',
            field=models.CharField(max_length=50, verbose_name='IBAN'),
        ),
    ]
