# Generated by Django 4.2.19 on 2025-02-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode', '0007_alter_profile_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresscode.dress')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresscode.size')),
            ],
        ),
        migrations.AddField(
            model_name='dressrental',
            name='dress_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dresscode.dresssize'),
        ),
    ]
