# Generated by Django 4.2.19 on 2025-02-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode', '0008_dresssize_dressrental_dress_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dressrental',
            name='dress_size',
        ),
        migrations.DeleteModel(
            name='DressSize',
        ),
    ]
